# Generated by Django 5.2.7 on 2025-11-17 03:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_configuracaocashback_alter_formapagamento_nome_and_more'),
        ('vendas', '0002_venda_observacao_vendaitem_delete_itemvenda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='valor_unitario',
            new_name='preco_venda',
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='venda',
            name='movimentacao_caixa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.movimentacao'),
        ),
    ]
