# Generated by Django 5.2.7 on 2025-11-03 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_divida_total_db_cliente_saldo_cashback_db'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='cliente_fornecedor',
            field=models.ForeignKey(blank=True, help_text='Cliente para Entradas; Fornecedor para Saídas.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente', verbose_name='Cliente/Fornecedor'),
        ),
    ]
