# Generated by Django 5.2.7 on 2025-11-17 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_divida_total_db_cliente_saldo_cashback_db'),
        ('financeiro', '0002_movimentacao_cliente_fornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoCashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashback_ativo', models.BooleanField(default=True, help_text='Marque para ativar o sistema de cashback.')),
                ('percentual_cashback', models.DecimalField(decimal_places=2, default=3.0, help_text='Percentual a ser gerado sobre o valor da venda (ex: 3.00 para 3%).', max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='formapagamento',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='cliente_fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data_lancamento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='forma_pagamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='financeiro.formapagamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='status',
            field=models.CharField(choices=[('PAGO', 'Pago'), ('PENDENTE', 'Pendente')], default='PAGO', max_length=10),
        ),
    ]
