# Generated by Django 5.2.7 on 2025-11-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Produto')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo Unitário Base (R$)')),
                ('custos_extras', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Custos Extras (R$)')),
                ('margem_lucro', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Margem de Lucro (%)')),
                ('valor_sugerido', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Final Sugerido (R$)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
