# Generated by Django 5.2.7 on 2025-10-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cashbackmovimento_venda_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apelido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
