# Generated by Django 5.2.7 on 2025-10-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0003_cliente_apelido_cliente_sobrenome"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="divida_total_db",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="cliente",
            name="saldo_cashback_db",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
